# Generated by Django 4.2.7 on 2023-11-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='親id')),
                ('sort', models.IntegerField(verbose_name='並び順')),
                ('quantity', models.IntegerField(default=None, null=True, verbose_name='数')),
            ],
            options={
                'verbose_name': '構成',
            },
        ),
        migrations.CreateModel(
            name='CompositionChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_list_app.composition', verbose_name='製品')),
            ],
            options={
                'verbose_name': '構成変更セット',
                'db_table': 'part_list_app_composition_change_set',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='部品コード')),
                ('name', models.CharField(max_length=255, verbose_name='部品名')),
            ],
            options={
                'verbose_name': '部品',
            },
        ),
        migrations.CreateModel(
            name='UndoRedoPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_list_app.compositionchangeset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_list_app.composition', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'UndoRedoPointer',
                'db_table': 'part_list_app_undo_redo_pointer',
            },
        ),
        migrations.CreateModel(
            name='CompositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_original_id', models.IntegerField()),
                ('parent_original_id', models.BigIntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('quantity', models.IntegerField(blank=True, default=None, null=True, verbose_name='数')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '更新'), ('delete', '削除')], max_length=50, verbose_name='操作')),
                ('status', models.CharField(choices=[('before', '前'), ('after', '後')], max_length=6, verbose_name='ステータス')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('composition_change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_histories', to='part_list_app.compositionchangeset')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='part_list_app.part', verbose_name='部品id')),
            ],
            options={
                'verbose_name': '構成履歴',
                'db_table': 'part_list_app_composition_history',
            },
        ),
        migrations.AddField(
            model_name='composition',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_compositions', to='part_list_app.part', verbose_name='部品'),
        ),
    ]
